plugins {
    id 'com.android.application'
}

android {
    namespace 'ai.ignition.android'
    compileSdk 36

    defaultConfig {
        applicationId "ai.ignition.android"
        minSdk 26
        targetSdk 36
        versionCode 1
        versionName "0.1.0-preview"
        testInstrumentationRunner 'com.ignitionai.nativeapp.NativeUiTest'
    }

    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
        coreLibraryDesugaringEnabled true
    }
    sourceSets.main.assets.srcDir rootProject.file('virtual-sensors/src/main/resources')
}

dependencies {
    implementation project(':native-core')
    coreLibraryDesugaring 'com.android.tools:desugar_jdk_libs:2.1.5'
    implementation 'androidx.appcompat:appcompat:1.6.1'
    implementation 'com.google.android.material:material:1.11.0'
    implementation 'androidx.constraintlayout:constraintlayout:2.1.4'
}
